apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@{{ .Release.Name }}-postgresql:5432/taskdb"
  REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379/0"
