{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: "{{ .Values.service.port }}"
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
